import Head from "next/head";
import { useState } from "react";
import { trpc } from "../utils/trpc";
var Home = function () {
    var _a = useState(""), value = _a[0], setValue = _a[1];
    var _b = trpc.useQuery(["resources.resources", { text: value }], {
        enabled: false,
    }), data = _b.data, refetch = _b.refetch;
    return (<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>

			<main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
				<div>
					<input type="text" className="p-2 empty:ring-2 empty:ring-green-400 rounded" value={value} onChange={function (e) { return setValue(e.target.value); }}/>
					<button onClick={function () {
            refetch();
        }}>
						查询
					</button>
				</div>

				{(data === null || data === void 0 ? void 0 : data.data) && (<div className="grid grid-cols-3 grid-rows-3">
						{data.data
                .filter(function (s) { return s.endsWith("mp4"); })
                .map(function (s) { return (<video key={s} src={s}></video>); })}
					</div>)}
			</main>
		</>);
};
export default Home;
var TechnologyCard = function (_a) {
    var name = _a.name, description = _a.description, documentation = _a.documentation;
    return (<section className="flex flex-col justify-center p-6 duration-500 border-2 border-gray-500 rounded shadow-xl motion-safe:hover:scale-105">
			<h2 className="text-lg text-gray-700">{name}</h2>
			<p className="text-sm text-gray-600">{description}</p>
			<a className="mt-3 text-sm underline text-violet-500 decoration-dotted underline-offset-2" href={documentation} target="_blank" rel="noreferrer">
				Documentation
			</a>
		</section>);
};
